---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: version
    image: golang:1.14.1
    commands:
      - make version
    environment:
      GO111MODULE: on
      GOPATH: /drone

  - name: deps
    image: golang:1.14.1
    commands:
      - make deps
    environment:
      GO111MODULE: on
      GOPATH: /drone
    depends_on:
      - version

  - name: build
    image: golang:1.14.1
    commands:
      - make build
    environment:
      GO111MODULE: on
      GOPATH: /drone
    depends_on:
      - deps

  - name: test
    image: golang:1.14.1
    commands:
      - make test
    environment:
      GO111MODULE: on
      GOPATH: /drone
    depends_on:
      - deps

  - name: docker-build
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export BUILD_VERSION="$(cat ./VERSION)"
      - docker build -t ollieparsley/twitter-api-metrics:$BUILD_VERSION -t ollieparsley/twitter-api-metrics:latest -f Dockerfile .
    depends_on:
      - build
      - test

  - name: docker-publish
    image: docker:latest
    commands:
      - export BUILD_VERSION="$(cat ./VERSION)"
      - docker login -u ollieparsley -p $DOCKER_PASSWORD
      - docker push ollieparsley/twitter-api-metrics:$BUILD_VERSION
      - docker push ollieparsley/twitter-api-metrics:latest
    depends_on:
      - docker-build
    when:
      event:
        - push
      branch:
        - master

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
